### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by amad3v** [uloco/bluloco.nvim#1]
Hi uloco,

I'm using this theme with `vscode` and I'd like to have it on `nvim` and `lunarvim` but failed to install it.
Could you please share how to do that on `nvim` or `lunarvim` and how to choose the variant?

**Comment by uloco** [comment]
Oh, my bad sorry. I didn't put this clear in the readme.
This is an early work in progress and not usable atm, sorry :/
I'm working continuosly on it whenever I got time.

Thank you for opening this issue. I'm glad people want to use this for neovim too :)

You can subscribe to the releases on this projet so you get notified when the first version is available.
After than it will be as easy as installing any other plugin with packer.

**Comment by uloco** [comment]
I think you can use it now. It is still a work in progress and a lot of plugins are missing (probably some you are using) but if you want you can try using it with packer like so:

```
use {
    'uloco/bluloco.nvim',
    requires = { 'rktjmp/lush.nvim' }
  }
```
To choose the variant, just set `vim.opt.background="light"` or `"dark"`
If you skip this step it auto adjusts to the current background (for example macos system settings)

Pleaes let me know of any issues / missing plugins etc. and I can see what I can do.

Thanks!

I will need to update the readme still. Will do so when it is more stable.

**Comment by amad3v** [comment]
It works with `lunarvim` and looks very nice.
Thank you!
![lvim](https://i.postimg.cc/021X5tP5/lvim.png)
