### ISSUE TITLE
Marketing

### ISSUE THREAD

**Issue by uloco** [uloco/bluloco.nvim#38]
- [x] add to [lush.nvim/README.md at main · rktjmp/lush.nvim · GitHub](https://github.com/rktjmp/lush.nvim/blob/main/made_with_lush/README.md#made-with-lush)
- [x] add to awesome-neovim
- [x] This week in neovim
- [x] prepare buy me a coffee
- [x] add bmac link in readme

**Comment by James-DeLorenzo** [comment]
@uloco Hi, see my above PR to lush.nvim repo for bullet point 1 here :)

**Comment by uloco** [comment]
Thanks mate!
