### ISSUE TITLE
background color of WinSeparator

### ISSUE THREAD

**Issue by tthkbw** [uloco/bluloco.nvim#48]
I use blueloco-dark and lualine with 'auto' setting. The background of the WinSeparator is very close to the background color of the windows so it is difficult for me to see that I have a split window.

I have tried to change this using:
```
hi WinSeparator ctermbg = #ffffff
```
as an example. I have termguicolors set. However, I can't apparently change the WinSeparator background color.

How do I make the WinSeparator a bit brighter so it is more obvious to my old eyes?

**Comment by uloco** [comment]
Try guibg instead of ctermbg. I'm on my phone right now and will only have time to look into it in the coming week...

**Comment by uloco** [comment]
@tthkbw Did this work for you?

**Comment by tthkbw** [comment]
Not really. I am primarily talking about the horizontal split, which is controlled by the status line I use. My WinSeparator changes do change the color of the vertical separator as expected, but the StatusLine remains the same. I looked at the StatusLine stuff and had no luck making it more apparent. I gave up and went on to more important things.

Thanks for checking.

**Comment by uloco** [comment]
What statusline plugin are you using, if any?

**Comment by tthkbw** [comment]
Thanks for the comment. This got me to thinking and I have solved the problem. 

I use lualine (https://github.com/nvim-lualine/lualine.nvim) and had the theme set to 'auto'. I scanned through all the available themes and settled on 'papercolor_light'. Good contrast when the pane is active with a distinctive blue background that contrasts well with my dark background. When the window is not active, the background of the statusline changes to white and is nicely visible.

Problem solved! 

And, this is not a bluloco problem.

**Comment by uloco** [comment]
But I do theme the bluloco statusline in lualine. That got me thinking too. So maybe I can improve this in the lualine config for bluloco aswell. thanks

**Comment by tthkbw** [comment]
Yes, I do see that now. the problem for me is that I want contrast in the status line to emphasize the split and its location. 

Lualine blanks the information on mode and so on when the window is inactive, which leaves the dark color background as the status line color and I can't distinguish it very well. 

Maybe you should allow configuring the light lualine setting even with dark backgrounds, a vice versa. 

My old eyes love contrast, one of the reasons I like bluloco.

**Comment by uloco** [comment]
Oh that's not a bad idea at all. I'll see what i can do

**Comment by uloco** [comment]
I tried to do it but it was just too distracting imo, sorry.
