### ISSUE TITLE
Add support for Semantic Highlighting in neovim 0.9

### ISSUE THREAD

**Issue by carlosflorencio** [uloco/bluloco.nvim#49]
Hi, 

This is a request to add support for the new semantic highlight groups in neovim 0.9 :).

Useful info: https://www.reddit.com/r/neovim/comments/12gvms4/this_is_why_your_higlights_look_different_in_90/

Thanks!

**Comment by carlosflorencio** [comment]
Thanks @uloco, looks neat!

**Comment by uloco** [comment]
Sure, if there are any issues with it, let me know.
