### ISSUE TITLE
Indent blankline updated to version 3

### ISSUE THREAD

**Issue by hankertrix** [uloco/bluloco.nvim#61]
[indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim) was updated to version 3, which changed quite a few things. The biggest one is that the highlight group for the scope now takes from the `LineNr` highlight group instead of the `Label` highlight group. A suggestion to restore the previous colour is to set the highlight group `IblScope` to take the colour from the `Label` highlight group, i.e.

```lua
-- In lush_theme/bluloco.lua
-- Inside the return value of the lush() function
IblScope = { Label },
```

Old version:
![image](https://github.com/uloco/bluloco.nvim/assets/91734413/9a837414-e5ec-42f7-b6ed-56685a8d15e2)

New version:
![image](https://github.com/uloco/bluloco.nvim/assets/91734413/0ba32945-275c-4a14-bf5f-97b84386b4ed)

**Comment by uloco** [comment]
Thanks for reporting, would you mind creating a PR?

**Comment by uloco** [comment]
I tried the latest version of indent blankline and it is grey like it used to. the only thing i see is that the indent char changed and I don't think I want to override that. probably it was a bug on their side and seems fixed. please check and let me know so we can close this issue. thanks

**Comment by hankertrix** [comment]
I think the grey colour is for the regular lines showing the indentation level. Those lines are fine, it's the line that is highlighted when you're in a specific scope that doesn't match the previous colour, which used to be blue but is currently grey. Currently, it's quite difficult to see the highlighted line as the unhighlighted line is also grey.

This is what it should look like if it matches the previous version's colour:
![image](https://github.com/uloco/bluloco.nvim/assets/91734413/6f657915-1528-420f-bba9-1e8c7e9cccdd)

What it currently looks like:
![image](https://github.com/uloco/bluloco.nvim/assets/91734413/e80d1040-64bc-4d57-80f2-063695cdbee8)

**Comment by uloco** [comment]
Oh I did not know that it supposed to be blue. I thought grey is good because it is thicker when in scope. I probably had this feature disabled in the past so did not notice it at all.
<img width="134" alt="image" src="https://github.com/uloco/bluloco.nvim/assets/8818340/299189cd-e94f-4a22-9f8f-1895dcf72415">

I like it in grey and think it is visible enough.
Changing the highlight in the ibl setup config is a good way to customize this in my opinion.

**Comment by hankertrix** [comment]
Ah I see. I’ll close the issue then. Thanks!
