### ISSUE TITLE
Regarding the color issue of inlay_hint

### ISSUE THREAD

**Issue by jinzhongjia** [uloco/bluloco.nvim#63]
Its background color is the same as the annotation, so it doesn't look clear enough. Maybe we can make the difference by deepening the background color of inlay_hint.

![image](https://github.com/uloco/bluloco.nvim/assets/41784264/a7d124ab-4d33-4484-8faf-c497049188dd)

**Comment by uloco** [comment]
I see. How about reversing colors? So bg and fg switch?

**Comment by jinzhongjia** [comment]
this theme https://github.com/projekt0n/github-nvim-theme do like this: 
![image](https://github.com/uloco/bluloco.nvim/assets/41784264/405fe16c-be83-4c4a-8497-de3bdefe5af0)

I don’t know much about neovim’s color. It seems like the bg is accentuated.

**Comment by jinzhongjia** [comment]
in https://github.com/Mofiqul/vscode.nvim, like this:
![image](https://github.com/uloco/bluloco.nvim/assets/41784264/6b17438a-ed77-4c6d-b1cb-fc5f4906bce1)
Annotations and inlayhint colors are completely different

**Comment by jinzhongjia** [comment]
> this theme https://github.com/projekt0n/github-nvim-theme do like this: ![image](https://user-images.githubusercontent.com/41784264/276843139-405fe16c-be83-4c4a-8497-de3bdefe5af0.png)
> 
> I don’t know much about neovim’s color. It seems like the bg is accentuated.

I think we can directly refer to its processing method, and the workload should be minimal.

**Comment by uloco** [comment]
> > this theme https://github.com/projekt0n/github-nvim-theme do like this: ![image](https://user-images.githubusercontent.com/41784264/276843139-405fe16c-be83-4c4a-8497-de3bdefe5af0.png)
> 
> > 
> 
> > I don’t know much about neovim’s color. It seems like the bg is accentuated.
> 
> 
> 
> I think we can directly refer to its processing method, and the workload should be minimal.

This one looks good

**Comment by uloco** [comment]
I was planning to add this at some point... did you solve it other way or why did you close?

**Comment by jinzhongjia** [comment]
This issue hasn't changed for a long time. I thought you didn't plan to add this feature.
Now I’m looking forward to the new features in the future

**Comment by uloco** [comment]
Just a lot on my plate. But I want to close all issues at some point ;)

**Comment by hankertrix** [comment]
> this theme https://github.com/projekt0n/github-nvim-theme do like this: ![image](https://private-user-images.githubusercontent.com/41784264/276843139-405fe16c-be83-4c4a-8497-de3bdefe5af0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NDcxMzksIm5iZiI6MTcwNTg0NjgzOSwicGF0aCI6Ii80MTc4NDI2NC8yNzY4NDMxMzktNDA1ZmUxNmMtYmU4My00YzRhLTg0OTctZGUzYmRlZmU1YWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDE0MjAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkM2IzNjg5NzkwNmMzMTU5OWE5NjBmZjg2ZWFhYzFlMWNlNDA5ZGFmNGIzZGE5M2Q1MjQwZGJiMTk0MGEwYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3BbK-mz1o3zVH-hIg3VL9eL8pxf9ZP37AzlLFkkzOsk)
> 
> I don’t know much about neovim’s color. It seems like the bg is accentuated.

<br>

This theme uses the `LspInlayHint` highlight group to implement it, here's the code:
https://github.com/projekt0n/github-nvim-theme/blob/067cb69b93957ace0d0d83811453b401d1fb672c/lua/github-theme/group/modules/native_lsp.lua#L19

All we need now is a suitable background colour for both the dark theme and the light theme and it should be done.

**Comment by uloco** [comment]
I want to test this but couldn't figure out how to enable the inlay hints....

**Comment by hankertrix** [comment]
I looked around and found that inlay hints are a Neovim nightly feature.
https://github.com/nvimdev/lspsaga.nvim/issues/1204

He uses his own plugin called LspUI in his configuration, and I'm not sure if his plugin uses Neovim nightly or Neovim stable, but installing his plugin might allow you to test it:
https://github.com/jinzhongjia/LspUI.nvim

@jinzhongjia would you mind providing a minimal config to display the inlay hints as well as some code examples to test it?

**Comment by jinzhongjia** [comment]
first, add this to lua_ls config(I use `nevim-lspconfig`), this will request lua_ls enable inlay_hint feature

```lua
    settings = {
        Lua = {
            hint = {
                enable = true,
                arrayIndex = "Enable",
                setType = true,
            },
            workspace = {
                checkThirdParty = false,
            },
        },
    },
```

Then install neovim `nightly`, and you can use this to enable inlay_hint easily:
`:lua vim.lsp.inlay_hint.enable(0, true)`
It will enable inlay_hint for current buffer(current buffer be represented by 0 )

use this to disable inaly_hint `:lua vim.lsp.inlay_hint.enable(0, false)`

**Comment by jinzhongjia** [comment]
The inlay_hint of my plugin is just a package for the official function, which is more convenient for management (such as opening and closing different types of files and temporarily closing them)

**Comment by jinzhongjia** [comment]
![image](https://github.com/uloco/bluloco.nvim/assets/41784264/caa44a97-45df-43a9-851d-7e513e6c323c)

just like this

**Comment by jinzhongjia** [comment]
I think these are enough for testing without the need to install additional plugins

**Comment by hankertrix** [comment]
> I want to test this but couldn't figure out how to enable the inlay hints....

@uloco Neovim stable has updated to 0.10.0 and inlay hints should be easily testable now.
