### ISSUE TITLE
Highlight search mode in leap like folke/tokyonight

### ISSUE THREAD

**Issue by guoliang** [uloco/bluloco.nvim#68]
In folke's tokyo night theme https://github.com/folke/tokyonight.nvim 
when running leap https://github.com/ggandor/leap.nvim it looks as following
![image](https://github.com/uloco/bluloco.nvim/assets/542598/19d47aa2-477c-4312-88bf-350e97a31ee7)

while with bluloco it looks as following
![image](https://github.com/uloco/bluloco.nvim/assets/542598/0229501e-5b5a-457e-8186-7fd4537d1ba2)

**Comment by uloco** [comment]
Why do you prefer the first one? I think in the current version it's easier to keep the syntax colors so you understand the code where you want to jump better. Altough I dont really like the highlight of the labels...

**Comment by uloco** [comment]
I'll add a bluloco style label

**Comment by guoliang** [comment]
I guess it’s a matter of taste. I thought it was quite clear, for instance, if I accidentally go into leap mode. But maybe the downside would be some difficulty in finding where to jump to, for when I actually want to use leap.
