### ISSUE TITLE
Broken completion colors when switching style

### ISSUE THREAD

**Issue by uloco** [uloco/bluloco.nvim#69]
![image](https://github.com/uloco/bluloco.nvim/assets/8818340/21a96168-fadf-4e35-95c6-8de859bb2f9b)

**Comment by uloco** [comment]
auto-dark mode is not the problem. it appears also when switching manually with `:colorscheme bluloco-dark` and `:colorscheme bluloco-light`

**Comment by guoliang** [comment]
I recently changed re-did my nvim config using kickstart.nvim as base. Now when I apply the `bluloco` with the following setup

```lua{
  "uloco/bluloco.nvim",
  dependencies = {
    "rktjmp/lush.nvim",
  },
  lazy = false,
  priority = 1000,

  config = function()
    require("bluloco").setup({
      style = "auto", -- "auto" | "dark" | "light"
      transparent = true,
      italics = true,
      terminal = vim.fn.has("gui_running") == 1, -- bluoco colors are enabled in gui terminals per default.
    })
  end,
},

```

The colorscheme doesn't gets applied. Is the above issue related maybe?

**Comment by uloco** [comment]
Are you setting the colorscheme after the config is setup?
Not sure if this is related...

**Comment by guoliang** [comment]
> Are you setting the colorscheme after the config is setup? Not sure if this is related...

not related, it was me forgetting to set `vim.opt.termguicolors = true`

**Comment by uloco** [comment]
Having a `vim.opt.pumblend` greater than 0 causes this issue. I could not find an issue inside the theme regarding this. It's probably a limitation of how the theme is loaded (lush?) Closing for now since I don't know how to fix it in the theme. If you have issues with this, try setting pumblend to 0.
