### ISSUE TITLE
Breaking highlight changes in treesitter

### ISSUE THREAD

**Issue by hankertrix** [uloco/bluloco.nvim#70]
Mainly:
- `@type.qualifier` → `@keyword.modifier`
- `@keyword.storage` → `@keyword.modifier`

I'm not sure why nvim tree-sitter keeps having breaking highlight changes, but here are the commits:

https://github.com/nvim-treesitter/nvim-treesitter/commit/998b230a77b544761bae8aa7518d40b91a5c9559
https://github.com/nvim-treesitter/nvim-treesitter/commit/dccf31f9b1fbbbd09e6720c7d8f5f1a2433fd32d
https://github.com/nvim-treesitter/nvim-treesitter/commit/5d75359a9ae20c492f96e6591e3a9e229d320c87

**Comment by uloco** [comment]
Thank you so much for keeping track of this and fixing!

**Comment by hankertrix** [comment]
You’re welcome!
