### ISSUE TITLE
Lack of highlight group for "TODO" in comments

### ISSUE THREAD

**Issue by Philogy** [uloco/bluloco.nvim#72]
The theme seems to color other special comment things just fine but not TODOs when connected to tree-sitter for some reason (this is with javascript + comment tree-sitter installed).
![image](https://github.com/uloco/bluloco.nvim/assets/21957732/1b603e74-24ca-4595-a44f-cdd67dd4d3d2)

I tested another theme (onedark) just to confirm that this is a bluloco + tree-sitter issue.

Disabling tree-sitter seems to bring back some TODO highlighting in bluloco:
![image](https://github.com/uloco/bluloco.nvim/assets/21957732/07c1470c-597f-4049-8ed8-09b2fb555fe5)

Appreciate you looking into this, thanks!

**Comment by uloco** [comment]
What TODO plugin are you using? I'm using `folke/todo-comments.nvim` and it works when there is a colon after TODO, like `TODO:` and `FIXME:`. You can also adjust the pattern it matches so you could make it work for your style as well.
I can't fix what treesitter is doing here so I advise for using that plugin. Otherwise I don't know what to do about this tbh.

**Comment by uloco** [comment]
My current todo-comment config is this:

```
local status, todo = pcall(require, "todo-comments")
if (not status) then return end

todo.setup({
  search = {
    command = "rg",
    args = {
      "--color=never",
      "--no-heading",
      "--with-filename",
      "--line-number",
      "--column",
      "--glob=!e2e",
      "--glob=!translations",
      "--glob=!*.json",
      "--hidden"
    },
    -- regex that will be used to match keywords.
    -- don't replace the (KEYWORDS) placeholder
    pattern = [[\b(KEYWORDS):]], -- ripgrep regex
    -- pattern = [[\b(KEYWORDS)\b]], -- match without the extra colon. You'll likely get false positives
  },
})

```

**Comment by Philogy** [comment]
Is that an extra plugin I need to install?
